In [9]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.datasets import load_iris
iris=load_iris()
X=iris.data
y=iris.target
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)
svm_model=SVC(kernel='rbf',C=1,gamma='scale')
svm_model.fit(X_train,y_train)
y_pred=svm_model.predict(X_test)
print(y_pred)
print('accuracy',accuracy_score(y_test,y_pred))
print('classification',classification_report(y_test,y_pred))
print('confusion',confusion_matrix(y_test,y_pred))


[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
accuracy 1.0
classification               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

confusion [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
